# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/ishfisav/wally_1/wally_1.runs/synth_1/wallypipelinedsoc.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param power.BramSDPPropagationFix 1
set_param chipscope.maxJobs 5
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xck24-ubva530-2LV-c

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/ishfisav/wally_1/wally_1.cache/wt [current_project]
set_property parent.project_path /home/ishfisav/wally_1/wally_1.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kv260_som:part0:1.4 [current_project]
set_property board_connections {som240_1_connector xilinx.com:kv260_carrier:som240_1_connector:1.3} [current_project]
set_property ip_output_repo /home/ishfisav/wally_1/wally_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/config/shared/BranchPredictorType.vh
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/config/shared/parameter-defs.vh
}
set_property is_global_include true [get_files /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/config/shared/BranchPredictorType.vh]
read_verilog -library xil_defaultlib -sv {
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/cvw.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ifu/bpred/RASPredictor.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/generic/adder.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/mmu/adrdec.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/mmu/adrdecs.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/aes/aes32d.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/aes/aes32e.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/aes/aes64d.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/aes/aes64e.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/aes/aes64ks1i.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/aes/aes64ks2.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/aes/aesinvmixcolumns32.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/aes/aesinvmixcolumns8.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/aes/aesinvsbox64.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/aes/aesinvsbox8.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/aes/aesinvshiftrows64.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/aes/aesmixcolumns32.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/aes/aessbox32.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/aes/aessbox8.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/aes/aesshiftrows64.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/uncore/ahbapbbridge.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ebu/ahbcacheinterface.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ebu/ahbinterface.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/lsu/align.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/alu.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/lsu/amoalu.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/generic/aplusbeq0.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/lsu/atomic.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/generic/binencoder.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/bmu/bitmanipalu.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/bmu/bitreverse.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/bmu/bmuctrl.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ifu/bpred/bpred.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ifu/bpred/btb.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ebu/buscachefsm.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ebu/busfsm.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/bmu/byteop.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/cache/cache.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/cache/cacheLRU.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/cache/cachefsm.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/cache/cacheway.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/uncore/clint_apb.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/bmu/clmul.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/bmu/cnt.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/comparator.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/controller.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ebu/controllerinput.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/generic/counter.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/generic/csa.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/privileged/csr.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/privileged/csrc.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/privileged/csri.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/privileged/csrm.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/privileged/csrs.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/privileged/csrsr.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/privileged/csru.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/postproc/cvtshiftcalc.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/datapath.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/generic/decoder.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ifu/decompress.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/mdu/div.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/postproc/divshiftcalc.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/mdu/divstep.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/lsu/dtim.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ebu/ebu.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ebu/ebufsmarb.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/lsu/endianswap.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/bmu/ext.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/extend.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fclassify.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fcmp.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fctrl.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fcvt.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fdivsqrt/fdivsqrt.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fdivsqrt/fdivsqrtcycles.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fdivsqrt/fdivsqrtexpcalc.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fdivsqrt/fdivsqrtfgen2.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fdivsqrt/fdivsqrtfgen4.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fdivsqrt/fdivsqrtfsm.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fdivsqrt/fdivsqrtiter.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fdivsqrt/fdivsqrtpostproc.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fdivsqrt/fdivsqrtpreproc.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fdivsqrt/fdivsqrtstage2.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fdivsqrt/fdivsqrtstage4.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fdivsqrt/fdivsqrtuotfc2.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fdivsqrt/fdivsqrtuotfc4.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fdivsqrt/fdivsqrtuslc2.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fdivsqrt/fdivsqrtuslc4cmp.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fhazard.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/postproc/flags.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fli.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/generic/flop/flop.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/generic/flop/flopen.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/generic/flop/flopenl.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/generic/flop/flopenr.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/generic/flop/flopenrc.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/generic/flop/flopr.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fma/fma.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fma/fmaadd.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fma/fmaalign.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fma/fmaexpadd.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fma/fmalza.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fma/fmamult.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/postproc/fmashiftcalc.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fma/fmasign.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fmtparams.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fpu.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fregfile.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fround.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/fsgninj.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/aes/galoismultforward8.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/aes/galoismultinverse8.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/uncore/gpio_apb.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ifu/bpred/gshare.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ifu/bpred/gsharebasic.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/hazard/hazard.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/mmu/hptw.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ifu/bpred/icpred.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/ieu.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ifu/ifu.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ifu/irom.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ifu/bpred/localaheadbp.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ifu/bpred/localbpbasic.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ifu/bpred/localrepairbp.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/lsu/lrsc.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/lsu/lsu.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/generic/lzc.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/mdu/mdu.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/mmu/mmu.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/mdu/mul.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/generic/mux.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/generic/neg.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/postproc/negateintres.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/postproc/normshift.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/generic/onehotdecoder.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/generic/or_rows.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/kmu/packer.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/packoutput.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/uncore/plic_apb.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/mmu/pmachecker.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/mmu/pmpadrdec.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/mmu/pmpchecker.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/bmu/popcnt.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/postproc/postprocess.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/generic/priorityonehot.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/privileged/privdec.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/privileged/privileged.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/privileged/privmode.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/privileged/privpiperegs.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/generic/mem/ram1p1rwbe.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/generic/mem/ram1p1rwbe_64x22.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/generic/mem/ram1p1rwbe_64x44.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/generic/mem/ram1p1rwe.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/generic/mem/ram2p1r1wbe.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/generic/mem/ram2p1r1wbe_1024x68.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/uncore/ram_ahb.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/aes/rconlut32.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/regfile.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/postproc/resultsign.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/postproc/round.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/postproc/roundsign.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ifu/bpred/satCounter2.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/sha/sha256.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/sha/sha512_32.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/sha/sha512_64.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/postproc/shiftcorrection.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/shifter.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/postproc/specialcase.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/uncore/spi_apb.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/uncore/spi_fifo.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ifu/spill.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/cache/subcachelineread.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/lsu/subwordread.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/lsu/subwordwrite.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/lsu/swbytemask.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/generic/flop/synchronizer.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/mmu/tlb/tlb.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/mmu/tlb/tlbcam.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/mmu/tlb/tlbcamline.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/mmu/tlb/tlbcontrol.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/mmu/tlb/tlblru.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/mmu/tlb/tlbmixer.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/mmu/tlb/tlbram.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/mmu/tlb/tlbramline.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/privileged/trap.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ifu/bpred/twoBitPredictor.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/uncore/uartPC16550D.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/uncore/uart_apb.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/uncore/uncore.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/unpack.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/fpu/unpackinput.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/mmu/tlb/vm64check.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/wally/wallypipelinedcore.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/bmu/zbb.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/bmu/zbc.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/kmu/zbkb.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/kmu/zbkx.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/kmu/zipper.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/kmu/zknde32.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/kmu/zknde64.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/kmu/zknh32.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/ieu/kmu/zknh64.sv
  /home/ishfisav/wally_1/wally_1.srcs/sources_1/imports/cvw/src/wally/wallypipelinedsoc.sv
}
add_files /home/ishfisav/wally_1/wally_1.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /home/ishfisav/wally_1/wally_1.gen/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ishfisav/wally_1/wally_1.gen/sources_1/bd/design_1/design_1_ooc.xdc]

add_files /home/ishfisav/wally_1/wally_1.srcs/sources_1/bd/design_2/design_2.bd
set_property used_in_implementation false [get_files -all /home/ishfisav/wally_1/wally_1.gen/sources_1/bd/design_2/ip/design_2_blk_mem_gen_0_0/design_2_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ishfisav/wally_1/wally_1.gen/sources_1/bd/design_2/design_2_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/ishfisav/wally_1/wally_1.srcs/constrs_1/imports/constraints/pins_wally.xdc
set_property used_in_implementation false [get_files /home/ishfisav/wally_1/wally_1.srcs/constrs_1/imports/constraints/pins_wally.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/ishfisav/wally_1/wally_1.srcs/utils_1/imports/synth_1/wallypipelinedsoc.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top wallypipelinedsoc -part xck24-ubva530-2LV-c
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef wallypipelinedsoc.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file wallypipelinedsoc_utilization_synth.rpt -pb wallypipelinedsoc_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
