# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/pins_wally.xdc

# Block Designs: bd/baremetal_block/baremetal_block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==baremetal_block || ORIG_REF_NAME==baremetal_block} -quiet] -quiet

# IP: bd/baremetal_block/ip/baremetal_block_axi_bram_ctrl_0_0/baremetal_block_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==baremetal_block_axi_bram_ctrl_0_0 || ORIG_REF_NAME==baremetal_block_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/baremetal_block/ip/baremetal_block_blk_mem_gen_0_0/baremetal_block_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==baremetal_block_blk_mem_gen_0_0 || ORIG_REF_NAME==baremetal_block_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/baremetal_block/ip/baremetal_block_ahblite_axi_bridge_0_0/baremetal_block_ahblite_axi_bridge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==baremetal_block_ahblite_axi_bridge_0_0 || ORIG_REF_NAME==baremetal_block_ahblite_axi_bridge_0_0} -quiet] -quiet

# XDC: /home/ishfisav/wally_1/wally_1.gen/sources_1/bd/baremetal_block/ip/baremetal_block_blk_mem_gen_0_0/baremetal_block_blk_mem_gen_0_0_ooc.xdc

# XDC: /home/ishfisav/wally_1/wally_1.gen/sources_1/bd/baremetal_block/ip/baremetal_block_ahblite_axi_bridge_0_0/baremetal_block_ahblite_axi_bridge_0_0_ooc.xdc

# XDC: /home/ishfisav/wally_1/wally_1.gen/sources_1/bd/baremetal_block/baremetal_block_ooc.xdc
